### ISSUE TITLE
Link is broken

### ISSUE THREAD

**Issue by knj20** [Azure/Cloud-Native#10]
**Describe the bug**
when i go to the Roadmap for #30Days, Learn Core Concepts it gives me a Not Found page
**To Reproduce**
1. Go to 'Roadmap for #30Days - Week1'
2. Click on 'Sep 02 - Learn Core Concepts'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jaspreet-commits** [comment]
I am also facing the same issue. I was so excited about this whole serverless  September  thing .

**Comment by nitya** [comment]
Thank you both for reporting this - I've removed the links for now and will update them as and when each day's post is published. Expect today's post to be published later tonight (in a few hours). Future days may have multiple posts a day in which case you may see more frequent updates. Subscribe to the [blog RSS feed](https://azure.github.io/Cloud-Native/blog/rss.xml) to get notified when the post is published
